// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Context.SP
{
    public partial class GetProductListResult
    {
        public int ID { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public byte CategoryID { get; set; }
        [StringLength(50)]
        public string CategoryName { get; set; }
        public short UnitID { get; set; }
        [StringLength(50)]
        public string UnitName { get; set; }
        [StringLength(50)]
        public string Description { get; set; }
        [Column("UnitPrice", TypeName = "decimal(10,2)")]
        public decimal UnitPrice { get; set; }
        public int StockQuantity { get; set; }
        public short SupplierID { get; set; }
        [StringLength(255)]
        public string SupplierName { get; set; }
    }
}
