// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Context.SP
{
    public partial class GetSalesOrderListResult
    {
        public int ID { get; set; }
        public string No { get; set; }
        public string Date { get; set; }
        [Column("Amount", TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string Note { get; set; }
        public string CustomerName { get; set; }
    }
}
