// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using API.Context.SP;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace API.Context.SP
{
    public partial interface IMKSSPContextProcedures
    {
        Task<List<GetProductListResult>> GetProductListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetSalesOrderListResult>> GetSalesOrderListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStockInListResult>> GetStockInListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspBarcodeScanResult>> uspBarcodeScanAsync(string barcode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspGenerateNoResult>> uspGenerateNoAsync(string tradeTypePrefix, DateTime? date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspGetDetailListByIdResult>> uspGetDetailListByIdAsync(int? tradeID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspGetPermissionListResult>> uspGetPermissionListAsync(int? roleID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspGetProductComboListResult>> uspGetProductComboListAsync(string name, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspGetSalesOrderItemListResult>> uspGetSalesOrderItemListAsync(int? tradeID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspGetUserPermissionListResult>> uspGetUserPermissionListAsync(string userName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspUserAddResult>> uspUserAddAsync(string name, string phoneNumber, string username, string email, string password, bool? active, string kTP, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspUserGetResult>> uspUserGetAsync(int? iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspUserLoginResult>> uspUserLoginAsync(string username, string password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> uspUserUpdateAsync(int? iD, string name, string phoneNumber, string username, string email, string password, bool? active, string kTP, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
