// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Context.SP
{
    public partial class uspGetUserPermissionListResult
    {
        public int ID { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
    }
}
