// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Context.SP
{
    public partial class uspGetDetailListByIdResult
    {
        public int ID { get; set; }
        public int? ProductID { get; set; }
        [StringLength(50)]
        public string Product { get; set; }
        [StringLength(255)]
        public string Supplier { get; set; }
        public short SupplierID { get; set; }
        [StringLength(50)]
        public string Barcode { get; set; }
        [Column("UnitPrice", TypeName = "decimal(10,2)")]
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
    }
}
