// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class AuditLog
{
    public long ID { get; set; }

    public string EntityName { get; set; }

    public string Action { get; set; }

    public string EntityId { get; set; }

    public string UserName { get; set; }

    public string IpAddress { get; set; }

    public string Changes { get; set; }

    public DateTime CreatedAt { get; set; }
}