// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class Complaint
{
    public int ID { get; set; }

    public int OrderID { get; set; }

    public int CustomerID { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ResolvedAt { get; set; }

    public string AdminNote { get; set; }
}