// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class Consignment
{
    public int ID { get; set; }

    public DateTime Date { get; set; }

    public string No { get; set; }

    public int SupplierID { get; set; }

    public string SalesPersonName { get; set; }

    public short StatusID { get; set; }

    public string Note { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal SoldAmount { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<ConsignmentItem> ConsignmentItems { get; set; } = new List<ConsignmentItem>();
}