// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class ConsignmentItem
{
    public int ID { get; set; }

    public int ConsignmentID { get; set; }

    public int ProductID { get; set; }

    public int Quantity { get; set; }

    public int SoldQuantity { get; set; }

    public int ReturnedQuantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal SellingPrice { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Consignment Consignment { get; set; }

    public virtual Product Product { get; set; }
}