// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class DeliveryOrderItem
{
    public int ID { get; set; }

    public int DeliveryOrderID { get; set; }

    public int SalesOrderItemID { get; set; }

    public int ProductID { get; set; }

    public int Quantity { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public virtual DeliveryOrder DeliveryOrder { get; set; }
}