// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class DeliveryOrder
{
    public int ID { get; set; }

    public string No { get; set; }

    public int SalesOrderID { get; set; }

    public short StatusID { get; set; }

    public int? DriverUserID { get; set; }

    public string DeliveryAddress { get; set; }

    public DateTime? AssignedAt { get; set; }

    public DateTime? DeliveredAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public virtual ICollection<DeliveryOrderItem> DeliveryOrderItems { get; set; } = new List<DeliveryOrderItem>();

    public virtual User DriverUser { get; set; }

    public virtual Trade SalesOrder { get; set; }
}