// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class Expense
{
    public int ID { get; set; }

    public DateTime Date { get; set; }

    public string No { get; set; }

    public string Category { get; set; }

    public string Description { get; set; }

    public decimal Amount { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }
}