// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class MarketplaceAccount
{
    public int ID { get; set; }

    public int CustomerID { get; set; }

    public string Email { get; set; }

    public byte[] PasswordHash { get; set; }

    public byte[] PasswordSalt { get; set; }

    public string CartJson { get; set; }

    public string WishlistJson { get; set; }

    public virtual Customer Customer { get; set; }
}