// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace API.Context.Table;

public partial class MKSTableContext : DbContext
{
    public MKSTableContext(DbContextOptions<MKSTableContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerDeposit> CustomerDeposits { get; set; }

    public virtual DbSet<Debt> Debts { get; set; }

    public virtual DbSet<DeliveryOrder> DeliveryOrders { get; set; }

    public virtual DbSet<DeliveryOrderItem> DeliveryOrderItems { get; set; }

    public virtual DbSet<Lookup> Lookups { get; set; }

    public virtual DbSet<PaymentIn> PaymentIns { get; set; }

    public virtual DbSet<PaymentOut> PaymentOuts { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }

    public virtual DbSet<PurchasePayment> PurchasePayments { get; set; }

    public virtual DbSet<PurchaseReturnItem> PurchaseReturnItems { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolePermission> RolePermissions { get; set; }

    public virtual DbSet<SalesOrderItem> SalesOrderItems { get; set; }

    public virtual DbSet<SalesReturnItem> SalesReturnItems { get; set; }

    public virtual DbSet<StockCount> StockCounts { get; set; }

    public virtual DbSet<StockCountItem> StockCountItems { get; set; }

    public virtual DbSet<StockInItem> StockInItems { get; set; }

    public virtual DbSet<Trade> Trades { get; set; }

    public virtual DbSet<TradeType> TradeTypes { get; set; }

    public virtual DbSet<Unit> Units { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("Category");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Customer__3214EC279240A7C4");

            entity.ToTable("Customer");

            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.ContactNumber).HasMaxLength(20);
            entity.Property(e => e.ContactPerson)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Note).IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(255);
        });

        modelBuilder.Entity<CustomerDeposit>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Customer__3214EC27D526C7FE");

            entity.ToTable("CustomerDeposit");

            entity.HasIndex(e => e.SupplierID, "UQ_CustomerDeposit_SupplierID").IsUnique();

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedBy).HasMaxLength(64);
            entity.Property(e => e.UpdatedBy).HasMaxLength(64);
        });

        modelBuilder.Entity<Debt>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Debt__3214EC278FEE98D6");

            entity.ToTable("Debt");

            entity.Property(e => e.AmountPaid).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DueDate).HasColumnType("date");
            entity.Property(e => e.PaymentDate).HasColumnType("date");
        });

        modelBuilder.Entity<DeliveryOrder>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Delivery__3214EC2782E7BE42");

            entity.ToTable("DeliveryOrder");

            entity.HasIndex(e => e.SalesOrderID, "IX_DeliveryOrder_SalesOrderID");

            entity.HasIndex(e => e.StatusID, "IX_DeliveryOrder_StatusID");

            entity.Property(e => e.AssignedAt).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.DeliveredAt).HasColumnType("datetime");
            entity.Property(e => e.DeliveryAddress)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.No)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.StatusID).HasDefaultValue((short)1);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.DriverUser).WithMany(p => p.DeliveryOrders)
                .HasForeignKey(d => d.DriverUserID)
                .HasConstraintName("FK_DeliveryOrder_User");

            entity.HasOne(d => d.SalesOrder).WithMany(p => p.DeliveryOrders)
                .HasForeignKey(d => d.SalesOrderID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DeliveryOrder_SalesOrder");
        });

        modelBuilder.Entity<DeliveryOrderItem>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Delivery__3214EC2701702C15");

            entity.ToTable("DeliveryOrderItem");

            entity.HasIndex(e => e.DeliveryOrderID, "IX_DeliveryOrderItem_DeliveryOrderID");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.DeliveryOrder).WithMany(p => p.DeliveryOrderItems)
                .HasForeignKey(d => d.DeliveryOrderID)
                .HasConstraintName("FK_DeliveryOrderItem_DeliveryOrder");
        });

        modelBuilder.Entity<Lookup>(entity =>
        {
            entity.ToTable("Lookup");

            entity.Property(e => e.Entity)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PaymentIn>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__PaymentI__3214EC2735E28B9F");

            entity.ToTable("PaymentIn");

            entity.HasIndex(e => e.CustomerID, "IX_PaymentIn_CustomerID");

            entity.HasIndex(e => e.SalesInvoiceID, "IX_PaymentIn_SalesInvoiceID");

            entity.HasIndex(e => e.SalesOrderID, "IX_PaymentIn_SalesOrderID");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy).HasMaxLength(64);
            entity.Property(e => e.Date)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("date");
            entity.Property(e => e.Method).HasMaxLength(32);
            entity.Property(e => e.No)
                .IsRequired()
                .HasMaxLength(32);
            entity.Property(e => e.Note).HasMaxLength(256);
            entity.Property(e => e.StatusID).HasDefaultValue((short)1);
            entity.Property(e => e.Type).HasMaxLength(16);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(64);

            entity.HasOne(d => d.Customer).WithMany(p => p.PaymentIns)
                .HasForeignKey(d => d.CustomerID)
                .HasConstraintName("FK_PaymentIn_Customer");

            entity.HasOne(d => d.SalesOrder).WithMany(p => p.PaymentIns)
                .HasForeignKey(d => d.SalesOrderID)
                .HasConstraintName("FK_PaymentIn_SalesOrder");
        });

        modelBuilder.Entity<PaymentOut>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__PaymentO__3214EC27FF3C12F4");

            entity.ToTable("PaymentOut");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedBy).HasMaxLength(64);
            entity.Property(e => e.Method).HasMaxLength(32);
            entity.Property(e => e.No)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.Note).HasMaxLength(256);
            entity.Property(e => e.ReferenceNo).HasMaxLength(64);
            entity.Property(e => e.Type).HasMaxLength(32);
            entity.Property(e => e.UpdatedBy).HasMaxLength(64);
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.ToTable("Permission");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("Product");

            entity.Property(e => e.Barcode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("date");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.UpdatedAt).HasColumnType("date");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PurchaseOrderItem>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Purchase__3214EC278D21C0CE");

            entity.ToTable("PurchaseOrderItem");
        });

        modelBuilder.Entity<PurchasePayment>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Purchase__3214EC272752EB26");

            entity.ToTable("PurchasePayment");

            entity.Property(e => e.AmountPaid).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PaymentDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("date");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(255);
        });

        modelBuilder.Entity<PurchaseReturnItem>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Purchase__3214EC270CBA3842");

            entity.ToTable("PurchaseReturnItem");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Role__3214EC27592650AE");

            entity.ToTable("Role");

            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__RolePerm__3214EC27D381C933");

            entity.ToTable("RolePermission");
        });

        modelBuilder.Entity<SalesOrderItem>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__SalesOrd__3214EC27E33F869F");

            entity.ToTable("SalesOrderItem");

            entity.Property(e => e.QtyExchanged).HasDefaultValue(0);
        });

        modelBuilder.Entity<SalesReturnItem>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__SalesRet__3214EC272E27791C");

            entity.ToTable("SalesReturnItem");

            entity.HasIndex(e => e.ExchangeSourceItemID, "IX_SalesReturnItem_ExchangeSourceItemID");

            entity.HasIndex(e => e.ProductID, "IX_SalesReturnItem_ProductID");

            entity.HasIndex(e => e.TradeID, "IX_SalesReturnItem_TradeID");

            entity.Property(e => e.RefundAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ReturnType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<StockCount>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__StockCou__3214EC27B632DCFD");

            entity.ToTable("StockCount");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.Date)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("date");
            entity.Property(e => e.No)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
        });

        modelBuilder.Entity<StockCountItem>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__StockCou__3214EC2703079B17");

            entity.ToTable("StockCountItem");

            entity.Property(e => e.UnitPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Product).WithMany(p => p.StockCountItems)
                .HasForeignKey(d => d.ProductID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StockCountItem_Product");

            entity.HasOne(d => d.StockCount).WithMany(p => p.StockCountItems)
                .HasForeignKey(d => d.StockCountID)
                .HasConstraintName("FK_StockCountItem_StockCount");
        });

        modelBuilder.Entity<StockInItem>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__StockInI__3214EC275A9D5844");

            entity.ToTable("StockInItem");
        });

        modelBuilder.Entity<Trade>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Trade__3214EC27E417F279");

            entity.ToTable("Trade");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("date");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Date).HasColumnType("date");
            entity.Property(e => e.NetDifference).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.No)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Note)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PaidAmount).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.UpdatedAt).HasColumnType("date");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TradeType>(entity =>
        {
            entity.ToTable("TradeType");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.No)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Unit>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Unit__3214EC27C1781765");

            entity.ToTable("Unit");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.KTP)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Password).HasMaxLength(100);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(13)
                .IsUnicode(false);
            entity.Property(e => e.UserName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("UserRole");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}