// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class Numbering
{
    public string Prefix { get; set; }

    public string DateKey { get; set; }

    public int LastNo { get; set; }
}