// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class PaymentIn
{
    public int ID { get; set; }

    public string No { get; set; }

    public DateTime Date { get; set; }

    public int? CustomerID { get; set; }

    public int? SalesOrderID { get; set; }

    public int? SalesInvoiceID { get; set; }

    public string Method { get; set; }

    public string Type { get; set; }

    public decimal Amount { get; set; }

    public string Note { get; set; }

    public short StatusID { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Trade SalesOrder { get; set; }
}