// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class PriceHistory
{
    public long ID { get; set; }

    public int ProductID { get; set; }

    public decimal OldPrice { get; set; }

    public decimal NewPrice { get; set; }

    public string ChangedBy { get; set; }

    public DateTime ChangedAt { get; set; }

    public string Source { get; set; }

    public string Note { get; set; }
}