// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class ProductVariant
{
    public int ID { get; set; }

    public int ProductID { get; set; }

    public string Name { get; set; }

    public int StockQuantity { get; set; }

    public virtual Product Product { get; set; }
}