// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class SalesReturnItem
{
    public int ID { get; set; }

    public int TradeID { get; set; }

    public int ProductID { get; set; }

    public int Quantity { get; set; }

    public string ReturnType { get; set; }

    public bool IsReplacement { get; set; }

    public int? ExchangeSourceItemID { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal RefundAmount { get; set; }

    public int? SourceSalesOrderItemID { get; set; }

    public int? QtyRefunded { get; set; }
}