// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class SalesPerson
{
    public int ID { get; set; }

    public int SupplierID { get; set; }

    public string Name { get; set; }

    public string Company { get; set; }

    public string Contact { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Consignment> Consignments { get; set; } = new List<Consignment>();

    public virtual Customer Supplier { get; set; }
}