// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class StockCountItem
{
    public int ID { get; set; }

    public int StockCountID { get; set; }

    public int ProductID { get; set; }

    public int SystemQty { get; set; }

    public int PhysicalQty { get; set; }

    public int DiffQty { get; set; }

    public decimal UnitPrice { get; set; }

    public virtual Product Product { get; set; }

    public virtual StockCount StockCount { get; set; }
}