// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Context.Table;

public partial class StockLedger
{
    public long ID { get; set; }

    public int ProductID { get; set; }

    public DateTime Date { get; set; }

    public string RefType { get; set; }

    public int? RefId { get; set; }

    public string RefNo { get; set; }

    public int QtyChange { get; set; }

    public int QtyAfter { get; set; }

    public string Note { get; set; }

    public string CreatedBy { get; set; }
}